# Generated by Django 2.1.1 on 2018-09-07 07:31

from django.db import migrations, models
import django.db.models.deletion
import exchanger_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('pk_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('pk_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=exchanger_api.models.timestamp_now)),
                ('status', models.IntegerField(choices=[(1, 'approved'), (2, 'declined'), (3, 'expired'), (4, 'processing'), (5, 'reversed')])),
                ('amount', models.FloatField(validators=[exchanger_api.models.check_amount_order])),
                ('currency', models.DecimalField(decimal_places=0, max_digits=3, validators=[exchanger_api.models.check_currency])),
                ('readable_id', models.CharField(max_length=256)),
                ('ord_type', models.IntegerField(choices=[(1, 'verification'), (2, 'purchase')])),
                ('description', models.CharField(max_length=500)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchanger_api.Merchant')),
            ],
        ),
    ]
